// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.IO;
[TestFixture]
public class InstaHack {
  
  private IWebDriver driver;
  private WebDriverWait wait;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;

  private string URL;
  private string USERNAME;
  private string PASSWORD;
  private int NUM_FRIENDS;

  [SetUp]
  public void SetUp() {
    string path = "C:\\Users\\Usuário\\Dropbox\\instahack\\driver";
    driver = new ChromeDriver(ChromeDriverService.CreateDefaultService(path));
    driver.Manage().Window.Maximize();
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(120);
    vars = new Dictionary<string, object>();
    js = (IJavaScriptExecutor)driver;

    //DADOS DE ENTRADA
    URL = "https://www.instagram.com/p/CDMd0YjFJKZ/";
    USERNAME = "";
    PASSWORD = "";
    NUM_FRIENDS = 2;
  }

  private void LimparMemoria () {
    string comando = "/C taskkill /F /IM chromedriver.exe /T";
    System.Diagnostics.Process.Start("CMD.exe", comando);
  }

  [TearDown]
  protected void TearDown() {
    LimparMemoria();
    driver.Quit();
  }

  protected void logar() {
    driver.Navigate().GoToUrl("https://www.instagram.com/");
    wait.Until(e => e.FindElement(By.Name("username")));
    driver.FindElement(By.Name("username")).Click();
    driver.FindElement(By.Name("username")).SendKeys(USERNAME);
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.Name("password")).SendKeys(PASSWORD);
    driver.FindElement(By.Name("password")).SendKeys(Keys.Enter);
  }

  protected void escrever(string msg) {
    driver.FindElement(By.XPath("//*[@id='react-root']/section/main/div/div[1]/article/div/div[3]/section[3]/div/form/textarea")).Click();
    driver.FindElement(By.XPath("//*[@id='react-root']/section/main/div/div[1]/article/div/div[3]/section[3]/div/form/textarea")).SendKeys(msg);
    driver.FindElement(By.XPath("//*[@id='react-root']/section/main/div/div[1]/article/div/div[3]/section[3]/div/form/button[2]")).Click();
  }

  protected void carregar() {
    driver.Navigate().GoToUrl(URL);
    Thread.Sleep(3000);
  }

  [Test]
  public void initHack() {
    wait = new WebDriverWait(driver, new TimeSpan(0, 5, 0));
    wait.IgnoreExceptionTypes(typeof(NoSuchElementException),typeof(InvalidOperationException));

    logar();
    wait.Until(e => e.FindElement(By.XPath("//*[@id='react-root']/section/main/div/div/div/section/div/div[1]/div/span")));

    carregar();
    
    using (StreamReader sr = new StreamReader("followinglist.csv"))
    {
        string currentLine;
        string msg = "";
        int tamanho = 0;
        while((currentLine = sr.ReadLine()) != null)
        {
          msg+="@"+currentLine+" ";
          tamanho++;
          if(tamanho == NUM_FRIENDS) {
            escrever(msg);
            tamanho = 0; msg = "";
            Thread.Sleep(5000);
            carregar();
            Thread.Sleep(5000);
          }
        }
    }
  }

}
